name:                csvquery
version:             0.1.0.0
github:              "AJChapman/csvquery"
license:             BSD3
author:              "Alex Chapman"
maintainer:          "alex@farfromthere.net"
copyright:           "Alex Chapman"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Simple parsing and querying of CSV files
category:            CSV

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/AJChapman/csvquery#readme>

dependencies:
- base >= 4.7 && < 5
- exceptions
- megaparsec >= 6.3.0 && < 7
- text
- boxes

library:
  source-dirs: src

executables:
  csvquery:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - csvquery
    - optparse-applicative

tests:
  csvquery-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - csvquery
